In [2]:
import numpy as np

In [ ]:
a = np.array([1, 3, 4], dtype=float)  # default type int

print(a)

print(type(a))

print(a.shape)  # 3

b = np.array([(1, 2, 3), (4, 5, 6)])

print(b)

print(b.shape)  # (2,3) row and column

c = np.zeros((2, 3))  # 2d arrays of zero  for 1d (2,)--< (0,0)
print(c)

d = np.ones((3, 4))
print(d)

e = np.full((4,), 8)  # 8 8 8 8
print(e)

f = np.eye(4)  # Identity Matrixx of 4X4
print(f)

g = np.random.random((4, 4))
print(g)

# 1 theke 100 er moddhe random value for 5X6 matrix
h = np.random.randint(1, 100, (5, 6))
print(h)

# 1 theke 10 er moddhe 5 ta vlaue with same space   1.    3.25  5.5   7.75 10.
i = np.linspace(1, 10, 5)
print(i)

j = np.arange(1, 10, 2)  # 1 3 5 7 9
print(j)


lst = [1, 2, 3, 4]
npar = np.asarray(lst)  # list to numpy array
print(type(npar))


# Analysis
print(d.shape)
print(d.ndim)  # dimension
print(d.dtype)  # type of data


# Math

x = np.array([1, 2, 3])
y = np.array([2, 3, 4])
z = x+y  # 3,5,7 which is not possible in list
z = x-y
z = x*y
z = x/y
print(np.add(x, y))
print(z)

# Manipulation

t = np.transpose(x)  # Transpose matrix or x.T

# tt = t.reshape((2, 3))  # Reshaping

[1. 3. 4.]
<class 'numpy.ndarray'>
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[8 8 8 8]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.20339983 0.75747518 0.69736685 0.009369  ]
 [0.19496167 0.82967201 0.4139528  0.82167453]
 [0.58103792 0.25933712 0.19839925 0.5867046 ]
 [0.21746302 0.70472881 0.28968828 0.97770875]]
[[ 4 20 69  9 40 35]
 [30 49  4 26 61 16]
 [46  6 18 59 51 90]
 [44 61 99 27 11 68]
 [58 44 75 31 97 45]]
[ 1.    3.25  5.5   7.75 10.  ]
[1 3 5 7 9]
<class 'numpy.ndarray'>
(3, 4)
2
float64
[3 5 7]
[0.5        0.66666667 0.75      ]


In [ ]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix)

a = np.arange(12)
# 3 by 4 matrix and if a.reshape() then original a no change ,,just copy change
a = a.reshape((3, 4))
print(a)
a.transpose()  # no change because it work on copy
b = a.transpose()
print(b)  # work
print(a)
a = a.flatten()  # bacck to original work on copy
# flatten and ravel are same but  raven return view instead of copy
print(a.ravel())  # return view instead of copy

[[1 2]
 [3 4]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Specific element", a[1, 2])
print("Entire row: ", a[1])
print("Entire col: ", a[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


Sorting


In [23]:
a = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(a))

b = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(b, axis=0))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]


Filter


In [25]:
n = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
ev = n[n % 2 == 0]
print("Even n", ev)
mask = n > 5
print("Numbers greater than 5 ", n[mask])

Even n [ 2  4  6  8 10]
Numbers greater than 5  [ 6  7  8  9 10]


Fancy

In [27]:

n = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

idx = [0, 2, 4]
print(n[idx])

ans = np.where(n > 5)
print(ans)  # indies
print("NP where", n[ans])


b = np.where(n > 5, "true",  "false")
print(b)

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


Adding and removing data

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))
print(c)

[1 2 3 4 5 6]



array compatibilty


In [30]:

a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes False


In [3]:

original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("With new column", with_new_col)

arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]
Array after deletion:  [1 2 4 5]
