In [1]:
import numpy as np

In [ ]:
a = np.array([1, 3, 4], dtype=float)  # default type int

print(a)

print(type(a))

print(a.shape)  # 3

b = np.array([(1, 2, 3), (4, 5, 6)])

print(b)

print(b.shape)  # (2,3) row and column

c = np.zeros((2, 3))  # 2d arrays of zero  for 1d (2,)--< (0,0)
print(c)

d = np.ones((3, 4))
print(d)

e = np.full((4,), 8)  # 8 8 8 8
print(e)

f = np.eye(4)  # Identity Matrixx of 4X4
print(f)

g = np.random.random((4, 4))
print(g)

# 1 theke 100 er moddhe random value for 5X6 matrix
h = np.random.randint(1, 100, (5, 6))
print(h)

# 1 theke 10 er moddhe 5 ta vlaue with same space   1.    3.25  5.5   7.75 10.
i = np.linspace(1, 10, 5)
print(i)

j = np.arange(1, 10, 2)  # 1 3 5 7 9
print(j)


lst = [1, 2, 3, 4]
npar = np.asarray(lst)  # list to numpy array
print(type(npar))


# Analysis
print(d.shape)
print(d.ndim)  # dimension
print(d.dtype)  # type of data


# Math

x = np.array([1, 2, 3])
y = np.array([2, 3, 4])
z = x+y  # 3,5,7 which is not possible in list
z = x-y
z = x*y
z = x/y
print(np.add(x, y))
print(z)

# Manipulation

t = np.transpose(x)  # Transpose matrix

tt = t.reshape(2, 3)  # Reshaping

[1. 3. 4.]
<class 'numpy.ndarray'>
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[8 8 8 8]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.76264355 0.34897212 0.23872704 0.64696669]
 [0.72920505 0.54027771 0.59960115 0.77605887]
 [0.77820745 0.01321815 0.03279819 0.37580836]
 [0.83007936 0.91563799 0.56757752 0.70816294]]
[[80 46 73 58 51 43]
 [41 27 90 32 78 88]
 [28 94 61 97 45 81]
 [99  9 13 54 32 74]
 [47 38 41 32  3 16]]
[ 1.    3.25  5.5   7.75 10.  ]
[1 3 5 7 9]
<class 'numpy.ndarray'>
(3, 4)
2
float64
[0.5        0.66666667 0.75      ]
